### ISSUE TITLE
About your Note

### ISSUE THREAD

**Issue by idrissneumann** [MohamedBechirMejri/uprodit-challenge#1]
Hi.

I'm the CTO of uprodit.com. Firstable I congratulate you for this work.

However I'd like to react to this par of your README:

> The challenge is by [uprodit](https://doc.uprodit.com/docs/challenge/), a simple search engine that can be created in a couple of hours with very advanced features IF THE API AND DOCS WERE USABLE. the api needs to be remade and the docs aren't useful.

I don't get how you can write this considering:
* You probably use [this documentation](https://doc.uprodit.com/docs/api/consume_api) to learn how to authenticate your client to our API and re-use our JS `generateSignature` method
* You succeed coding the first part of the challenge:

<img width="1397" alt="Screenshot 2022-10-24 at 18 34 05" src="https://user-images.githubusercontent.com/12884347/197589667-d45faad3-cd95-4399-b694-d46f39a631fd.png">

To be able to achieved that, you probably used our documentation (either with the postman collections we provided, either using the challenge insights):

<img width="966" alt="Screenshot 2022-10-24 at 18 35 04" src="https://user-images.githubusercontent.com/12884347/197589822-5690dd57-063c-4d31-ad39-faa032168a58.png">

We gave a very fine level of details with more insights and tutorials for the endpoints that are useful for implementing this challenge. Autocomplete and filters weren't part of what's asked in this challenge.

However we're still providing a WADL file which contains all the endpoints: https://api.uprodit.com

For example for the autocompletion:

<img width="757" alt="Screenshot 2022-10-24 at 18 38 51" src="https://user-images.githubusercontent.com/12884347/197590534-9a21ac82-06f8-481b-8a0c-ff0e7c2f2a0b.png">

WADL is an older standard that swagger or openapi but uprodit is almost a 10 years old project ;-)

WADL still allow you to generate your http client in several technologies (you can even generate swagger or openapi files with a wadl input).

Considering that:
* You used this documentation a lot to achieve the challenge
* The API is working very fine on your search engine
* The features you're considering not working are working fine in the [original search engine](https://www.uprodit.com/profile/all/search/perso)

<img width="1394" alt="Screenshot 2022-10-24 at 19 03 41" src="https://user-images.githubusercontent.com/12884347/197594801-b70a489f-a9fb-4f68-bf73-366af2eb03ab.png">

So, I find a little bit rude and unjustified to wrote that:
* the API isn't working (especially when she works and used by several clients and customers, you also can find other challenges implementations on github with opensources licences in Vue.JS or React)
* the API need to be rewrite without any explanation (for what purpose ? which value it will bring ? which return of investment ? Again it's a 10yo production project, not a PFE we can redo each years) 
* the documentation isn't useful, especially when you used it (directly or indirectly) ;-)

Of course a documentation isn't always enough for getting the sufficient level of details and sometimes some users needs other endpoints and features. That's why we also provide a Slack workspace were you can ask questions and get answers, you could also sign up with uprodit and contact the team there. We didn't receive any question from you, this contributes to the fact that I find your opinion on this matter too quickly frozen ;-)

Anyway I still congratulates you for your proposition, and feel free to join our Slack if you want to improve it: https://join.slack.com/t/uprodit-tech/shared_invite/zt-1h3hh21tf-Rxb4zbSiRz8GFVwXvqLHMA

We're always glad to help and share insights.

N.B: you should push a LICENCE file to your project :)

**Comment by MohamedBechirMejri** [comment]
Hello,

Thank you for your feedback.

First of all, I don't see why my comments seem rude to you, but I must apologize for any offence taken.

The note wasn't a feedback to the team requesting a change to the docs or api. I'm just giving a reason why it took me 6 hours to make a simple search bar. most of the time was wasted trying to understand what the docs are saying. for example:

![image](https://user-images.githubusercontent.com/76930306/197673801-472ac72a-847a-4f84-97dd-acd5ff685a0d.png)

What does usecase mean ? what are the possible uscases ? and why does it only return successful response ? 


Which brings me to the api, the only response I get from the api when there is an error is 401 Forbidden. 
This was one of the most frustrating things for me, I make a simple typo and I get 401 instead of a bad request with the actual error message. 

And as you said, this is acceptable in a pfe not in a 10 years old project. 

also having to request the images separately was inconvenient and it makes the front end feel slower you show the results then load the images (even on the original website). 

Anyway, if the api and docs feel good to you and others who are using it then congrats, I just noted that I didn't have a fun nor smooth experience using it. 

But if you regularly have new customers who use this api then I recommend making a few design changes in a v3, not entirely remake it.

About the License, thanks for the heads up.

**Comment by idrissneumann** [comment]
> What does usecase mean ? what are the possible uscases ? and why does it only return successful response ?

It was specified here in the challenge: https://doc.uprodit.com/docs/challenge#restful-endpoints-to-use

<img width="844" alt="Screenshot 2022-10-25 at 12 24 44" src="https://user-images.githubusercontent.com/12884347/197760572-96bc7742-34a9-4e36-a4a9-105b483572bc.png">

And following the doc and wadl, it works pretty fine:

<img width="1087" alt="Screenshot 2022-10-25 at 12 22 53" src="https://user-images.githubusercontent.com/12884347/197760484-3c611f48-5373-4b57-9ee6-b82ee6369439.png">

My point is : writing publicly that the "doc isn't useful" and "all the API needs to be rewrite" especially when you used it to achieve this challenge without contacting the team is unjustified and rude yes.

> And as you said, this is acceptable in a pfe not in a 10 years old project.

Are you at least 10yo experienced to say that ? If you are, you should know about the concept of "return of investment".

When we started, Restful weren't the most common web standard, neither were oauth or jwt (jwt and oauth 2.0 didn't exists that time and oauth 1.0 weren't the standard used by all the tech companies). So that time we developed our own [authentication framework for SAOP and REST API in opensource](https://ws-cxf-ext.github.io/ws-cxf-ext/). 

It's based on the JSR standard which were most follow that time and it's still use by big companies nowadays. I'm still maintaining it for this reason and I'm not using it anymore on our new projects because since then there is most adopted standards.

If you follow us you'll find that we're working on new SaaS project with most modern standard (jwt, oauth, swagger or openapi instead of wadl, etc). For the uprodit part, it's a project we maintained up to date in terms of versions and deployment (last versions of Spring framework, openjdk, vert.x, elasticsearch, etc) and we still add new features and rewrite some part to get a better user experience. 

During the years, many developers asks us to rewrite the part that still working fine nowadays using new languages and frameworks following some sort of hypes and regardless of the return of investment. I.e : rewrite all the frontend with Backbone and gulp, then with Angular.JS, then with React, etc. We used Angular and now we're using React and Vue on new projects. However, rewriting a software should only be motivated by the value delivered to the customers and, the return of investment and the time to market improvement.

My point is : if the project's still alive 10 years later, it's mainly because we focus on delivering new feature and not rewrite the existing one all the time. And it's also because we choose resilient design 10 years ago (when people told us Restful api weren't suitable for websites and social networks) and we're still good in terms of time to market and scalability with the choices we've made. On the contrary, we were pioneer of some choice which are still seen as "new techniques" nowadays (like Elasticsearch we used with the 1.0 version less than one year after it's creation). And we still improve our processes (introducing vert.x, containers and scalability, ci/cd automation, etc) and we have to deal with priority.

On the contrary a new project (including PFE) should consider most recent technologies and standard and not those of 10 years ago ;) . And of course choose those with the experience of durability and reliability and not just the hype.

> I don't see why my comments seem rude to you, but I must apologize for any offence taken.

> The note wasn't a feedback to the team requesting a change to the docs or api. I'm just giving a reason why it took me 6 hours to make a simple search bar.

And yet you wrote that on a public repo without valid arguments other than that "I didn't have fun and I have to try and search for 3 hours". 

A request change would be more polite though, we could explain why we can't afford rewriting all the project to make new generations of developers more comfortable every year. And as I said, judging without asking for help to the team is pretty quick ;)

Moreover, sometimes our work is to maintain legacy projects and deal with it, 3 hours of research for using a 10yo API the first time is totally normal for an engineer and there's still is more older projects to deal with.

And yes we're not close to rewrite all the interface contract but it has a non-negligeable cost, which needs to be financed with a real return on investment. I hope you'll understand why "I had to try during three hours for making a searching bar" is not a sufficient value for us. We don't have the investment capacity of Facebook or Twitter and I'm pretty sure people take at least the same time to discover their API (and days for getting a validated access by the way).

**Comment by idrissneumann** [comment]
> also having to request the images separately was inconvenient and it makes the front end feel slower you show the results then load the images (even on the original website).

We prefer to let the frontend print the results before getting the images asynchronously. All the data in a single webservice would explode the size of the http payloads (requesting to reduce the paging size) and we find it better to get pre-loaded results and asynchronous loading of image than waiting a more longer time to get synchronously all the results.

**Comment by MohamedBechirMejri** [comment]
This was the only useful part:

![image](https://user-images.githubusercontent.com/76930306/197795539-661f52bd-fd59-4f67-9ae1-2a82d1548b46.png)

But it wasn't enough to create this:

![image](https://user-images.githubusercontent.com/76930306/197795745-b15606b4-4304-49ac-9869-90d9189c1d45.png)

And no matter what i tried, all I get is a 401 Unauthorized Response. At the very least the server should return the error it logs. And that doesn't require "investment", the time it takes to implement this is less than the time you "invested" replying to a note nobody will see.

But again, if you think your api is good then good for you. I still think the docs are terrible and the api is unusable for a good search engine unless you don't care about the "return of investment" and you prefer wasting a couple of days trying to understand it on your own. 

> My point is : writing publicly that the "doc isn't useful" and "all the API needs to be rewrite" especially when you used it to achieve this challenge without contacting the team is unjustified and rude yes.

> writing publicly, unjustified , rude

You have released a product, receiving criticism is part of the "return of investment", you shouldn't get offended by a simple feedback or a small note nobody will notice. instead you might try to fix the product's flaws or as you said simply accept that it's not perfect but it's not popular enough to put money into improving it.

> used it to achieve this challenge

I did not achieve the challenge, I wasted more time than I should (again, "return of investment") implementing just one feature and dropped the rest because they only return errors.

> without contacting the team

I've used many apis old and new and never had to contact the team to ask about how I should work with it. The docs explain everything (and they're usually shorter so they don't require much "investment"). and if I misuse the api or make a typo... I always receive the error message which helps me fix the problem quickly and go back to the main task.

Also if contacting the team would offend them like this, I'd rather skip low quality products and be done with it.I could've "invested" the time I wasted on this challenge making my own api for the guy. 

Anyway I don't see any point "investing" in this conversation. you were offended by the notes, they weren't meant for ruining anyone's reputation. I wrote them for the guy who's checking out my code to tell him why the app wasn't as good as I originally planned. maybe I should've told him in the email but I didn't expect anyone to view this repo. my profile isn't famous and this repo will be long gone when I become popular. 

At the same time offering help or simply asking that I offer a more detailed feedback would've been better and would've made me retract my comments so maybe try to be friendlier to people who use your products.

**Comment by idrissneumann** [comment]
> This was the only useful part:

So now there's as at least one useful part, are you starting to admit you were dishonest writing this documentation you used isn't useful or shall I continue to demonstrate all your arguments are unfounded ?

For example, the fact that you also used [this other part of the documentation](https://doc.uprodit.com/docs/api/consume_api#api-authentication) to implement the `generateSignature` function. This is still useful ?

My point is it seems you're not honest enough to admit that you exaggerated on the negativity on your note you wrote. 

And yet I demonstrate you that all your arguments are unfounded and that's my answer's right when people wrote unfounded critics. All the lacks you were complaining were on the documentation (the `usecase`, the wadl file, etc). 

And if you take the time to search "uprodit" on github or azure devops repo, you could see that other people succeed perform the challenge very well using the same "unuseful" documentation. And we we're able to kindly propose our help to some of them.

There's also one of them which is a perfect reproduction using vue.js of our search engine.

> I've used many apis old and new and never had to contact the team to ask about how I should work with it. The docs explain everything (and they're usually shorter so they don't require much "investment"). 

That's because you're not experienced enough IMHO. If there's devrel, chats and forum that are full of questions and answer for each API or opensource project, there's probably a reason. And the most appreciated mindset is to contribute in this case, because in case if you didn't noticed you're not a uprodit customer ;)

> I could've "invested" the time I wasted on this challenge making my own api for the guy.

That's still because you're not experienced enough : the "other guy" is probably evaluating your ability to deal with API that are already developed by other teams. For a recruiter, this is a more valuable skills than making all the work by yourself because "it's more fun" and demonstrating you're not a good fit to work in a distributed team and re-use existing project with a community behind.

> At the same time offering help or simply asking that I offer a more detailed feedback would've been better and would've made me retract my comments so maybe try to be friendlier to people who use your products.

You reversed the roles, that's very convenient: it's you who didn't ask for help, didn't explain that you weren't able to make the autocompletion working with arguments. For example you could wrote "the autocompletion is not working because I can't found which usecase I shall use", "I obtain 401 errors and I don't know why"... 

But no, you just wrote it's because the documentation is useless and the API needs a complete rewriting, no questioning, no hindsight to find out if others have succeeded, no contribution spirit and only free negativity...

And yet, I still offered my help in my previous messages but seems you're still seems not honest enough to see it, so I'll remember you the help I just propose earlier:
* I gave you an invitation on a Slack workspace where we're glad to answer questions and help and receive polite requests for change
* I gave you the complete and detailed answer on how to use the `autocomplete` endpoint with an example of working curl. There's no issue with this endpoint, regardless of the "fun" you lacks ;)

To conclude: **I really don't care if you're retracting your comment or not**, I only wrote this issue because I found very curious on the reason this not and also because I wanted to help you technically (so did I) and advise you to adopt a more polite and constructive approach when something bothers you next time, because this kind of behaviour will not be well received by someone else's projects and free contributions. That's it for now, I'm closing this debate.

**Comment by MohamedBechirMejri** [comment]
you can keep your advice to yourself, and focus on learning how to program instead of wasting people's time. I wasn't being dishonest (I don't need to be), your api is as bad as your manners (and your english xD), you know it.

>  this kind of behaviour will not be well received by someone else's projects and free contributions.

No worries it's only received by crappy devs who care about 'return of investment' more than quality. (invest in your manners).

>  I wanted to help you technically 

Clearly I didn't ask for help. and you didn't help you were just defending your low quality product

> And if you take the time to search "uprodit" on github or azure devops repo, you could see that other people succeed perform the challenge very well using the same "unuseful" documentation. And we we're able to kindly propose our help to some of them.

Don't need to. The main website itself is bad and feels outdated.

Stop commenting on my repo. get a life.
